trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals DESKTOP-BKN0CUK

steps:
- script: echo "Hello from $(Agent.Name)" > artifact.txt
  displayName: 'Create simple artifact file'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifact.txt'
    ArtifactName: 'simple-artifact'
    publishLocation: 'Container'
