trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "This is a test artifact" > test-artifact.txt
  displayName: 'Create Test Artifact'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/drop' # Or the path to your build output
    artifact: 'TestArtifact' # A descriptive name for your artifact
    publishLocation: 'Container' # Or 'FilePath' if publishing to a file share
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/test-artifact.txt'
    ArtifactName: 'test-artifact'
    publishLocation: 'Container'