trigger:
- main

pool:
  name: 'Default'          # pool name (Default or custom)
  demands:                 # optional â€” ensure it runs on a specific agent
  - agent.name -equals DESKTOP-BKN0CUK

steps:
- script: echo "This is a test artifact" > test-artifact.txt
  displayName: 'Create Test Artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/test-artifact.txt'
    ArtifactName: 'test-artifact'
    publishLocation: 'Container'
